/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	throttlecontroller_v1alpha1 "github.com/xychu/throttle/pkg/apis/throttlecontroller/v1alpha1"
	versioned "github.com/xychu/throttle/pkg/client/clientset/versioned"
	internalinterfaces "github.com/xychu/throttle/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/xychu/throttle/pkg/client/listers/throttlecontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GPUQuotaInformer provides access to a shared informer and lister for
// GPUQuotas.
type GPUQuotaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GPUQuotaLister
}

type gPUQuotaInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGPUQuotaInformer constructs a new informer for GPUQuota type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGPUQuotaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGPUQuotaInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGPUQuotaInformer constructs a new informer for GPUQuota type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGPUQuotaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ThrottlecontrollerV1alpha1().GPUQuotas(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ThrottlecontrollerV1alpha1().GPUQuotas(namespace).Watch(options)
			},
		},
		&throttlecontroller_v1alpha1.GPUQuota{},
		resyncPeriod,
		indexers,
	)
}

func (f *gPUQuotaInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGPUQuotaInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gPUQuotaInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&throttlecontroller_v1alpha1.GPUQuota{}, f.defaultInformer)
}

func (f *gPUQuotaInformer) Lister() v1alpha1.GPUQuotaLister {
	return v1alpha1.NewGPUQuotaLister(f.Informer().GetIndexer())
}
